{% set name = "fs.webdavfs" %}
{% set version = "0.3.3" %}
{% set sha256 = "32777ec3a5a276aaf555b4ec303d06c4c26f1e67bcd8475fb07b3566f276ea2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.python.org/packages/b6/2c/4eb38309d71218e0ca4364db52240695497f488fee60563e37f46a8736d8/fs.webdavfs-0.3.3.zip
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - nose

  run:
    - python
    - fs
    - webdavclient2
    - furl
    - dateutil

test:
  imports:
    - webdavfs.webdavfs
    - webdavfs.opener

about:
  home: https://github.com/PyFilesystem/webdavfs
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'fs.webdavfs is a WebDAV driver for PyFileSystem2.'
  description: |

    Usage:
    ======

    > from webdavfs.webdavfs import WebDAVFS
    > url = 'http://zopyx.com:22082'
    > creds = dict(login='admin', password='admin')
    > root = '/exist/webdav/db'
    > handle = WebDAVFS(url, cred, root)
    > handle.makedir('foo')
    > print(handle.listdir('.'))
    ....

  doc_url: https://github.com/PyFilesystem/webdavfs
  dev_url: https://github.com/PyFilesystem/webdavfs

extra:
  recipe-maintainers:
    - ReimarBauer
