{% set name = "fs.webdavfs" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fs.webdavfs-{{ version }}.zip
  sha256: 282ebe9deb752cf071b9d2f6f85675de9cf05aa28b3a05f4689a7aac5637f3ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nose
    - pip
    - python >=3.6
  run:
    - cachetools
    - fs >2.0
    - python >=3.6
    - python-dateutil
    - webdavclient3

test:
  imports:
    - webdavfs
    - webdavfs.webdavfs
    - webdavfs.opener
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/PyFilesystem/webdavfs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebDAV support for pyfilesystem2
  doc_url: https://github.com/PyFilesystem/webdavfs
  dev_url: https://github.com/PyFilesystem/webdavfs

extra:
  recipe-maintainers:
    - ReimarBauer
