{% set name = "fs.webdavfs" %}
{% set version = "0.4.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fs.webdavfs-{{ version }}.tar.gz
  sha256: a193ca5d348d238c42f78fa842527d48799842d8c0cf7b2a76d473d54f38a757

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nose
    - pip
    - python >=3.6
  run:
    - cachetools
    - fs >2.0
    - python >=3.6
    - python-dateutil
    - webdavclient3

test:
  imports:
    - webdavfs
    - webdavfs.webdavfs
    - webdavfs.opener
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/PyFilesystem/webdavfs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebDAV support for pyfilesystem2
  doc_url: https://github.com/PyFilesystem/webdavfs
  dev_url: https://github.com/PyFilesystem/webdavfs

extra:
  recipe-maintainers:
    - ReimarBauer
