{% set name = "fs.webdavfs" %}
{% set version = "0.4.1" %}
{% set sha256 = "068b86899e35f2dd1a7eeacb8c67234443f1adbe353e2ec019cc412ba6e96090" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - nose
  host:
    - python
    - pip
    - setuptools
    - nose
  run:
    - python
    - fs
    - webdavclient2
    - furl
    - python-dateutil
test:
  imports:
    - webdavfs.webdavfs
    - webdavfs.opener

about:
  home: https://github.com/PyFilesystem/webdavfs
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: fs.webdavfs is a WebDAV driver for PyFileSystem2.
  description: |4

    Usage:
    ======

    > from webdavfs.webdavfs import WebDAVFS
    > url = 'http://zopyx.com:22082'
    > creds = dict(login='admin', password='admin')
    > root = '/exist/webdav/db'
    > handle = WebDAVFS(url, cred, root)
    > handle.makedir('foo')
    > print(handle.listdir('.'))
    ....

  doc_url: https://github.com/PyFilesystem/webdavfs
  dev_url: https://github.com/PyFilesystem/webdavfs

extra:
  recipe-maintainers:
    - ReimarBauer
