appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ot9fZ+y+DI5bnnO1FNrQ80dAmQ9l7f4Ggu3u/7XSM44M9OR/mgpo8zCSudTwXBFe07cwVWespUEMbh37jNPtlMO8mIxn/3CZpRaju8nxo9ysq7rRpcrN2g+UoCl5Rx0AbjRYoa6QcMi1k1STTAD7MPW/2TJj6H6/En8crjjnhRL73ViFqqKHDxj+DT8KVfaSrKj5tD3jhzzjxgMQfhZnIVdtn5ls4K/Ec1dY1rZjp9XdYMrqkWCkizIZM7r5SD06GlJGlKTPaAbomQFHTblumrpSjdNzh7m5MTXA9Azu3VKJLo2hlMrIG2jmlEnsN4Y4Va/yG+QNMhsLN6SPyi2vL8ZKH0+Rls34Pudl7J9xNy778M8pIlaNyuquAiBF+0HwgKyjWLoj8qtAv9JbeecWuisp17h+dpgn0bkaIni9lsNi6xoFrxQ8E22uBDaoFz++SCn0PDkwFDNZj4xSWTtoR//ocxYL9eXhyJvD2eHTE1JHMNcYbgSoJAoe39YjiucUGsH+ZlGB0q/71rcdVEYCcBaEPcpjc2LwYtIObSoI4A24B0F5rU87MbGGPb3QXUbwITUYqiPPoc5JZ2GikHW+e5VE1Iml/7kZYLwIX6sg4qSiQA3am1NGtErfHbso/UcClY9z6b4evyIfo0SdOHairhnLULsHtTyBYCHa/1uQFpE=}
provider:
  win: azure
